# Generated by Django 4.1.3 on 2023-03-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collagestoreapp', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='emailid',
        ),
    ]
