# Generated by Django 4.1.3 on 2023-03-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collagestoreapp', '0005_alter_register_email_alter_register_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
    ]
