# Generated by Django 4.1.3 on 2023-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collagestoreapp', '0006_remove_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.IntegerField(null=True),
        ),
    ]
