# Generated by Django 4.1.3 on 2023-03-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collagestoreapp', '0007_register_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
